export const SORT_PRICE_BEGIN = 'SORT_PRICE_BEGIN';
export const SORT_PRICE_END = 'SORT_PRICE_END';
export const SORT_BY_ALPHABET_BEGIN = 'SORT_BY_ALPHABET_BEGIN';
export const SORT_BY_ALPHABET_END = 'SORT_BY_ALPHABET_END';
